// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RentalSystem.Entities;

[Table("RentalEquipment")]
public partial class RentalEquipment
{
    [Key]
    public int RentalEquipmentID { get; set; }

    [Required]
    [StringLength(20)]
    public string ModelNumber { get; set; }

    [Required]
    [StringLength(20)]
    public string SerialNumber { get; set; }

    [Required]
    [StringLength(50)]
    public string Description { get; set; }

    [Column(TypeName = "smallmoney")]
    public decimal DailyRate { get; set; }

    [StringLength(100)]
    public string Condition { get; set; }

    public bool Available { get; set; }

    public bool Retired { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [InverseProperty("RentalEquipment")]
    public virtual ICollection<RentalDetail> RentalDetails { get; set; } = new List<RentalDetail>();
}