// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ReceivingSystem.Entities;

public partial class PurchaseOrderDetail
{
    [Key]
    public int PurchaseOrderDetailID { get; set; }

    public int PurchaseOrderID { get; set; }

    public int StockItemID { get; set; }

    [Column(TypeName = "money")]
    public decimal PurchasePrice { get; set; }

    public int Quantity { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("PurchaseOrderID")]
    [InverseProperty("PurchaseOrderDetails")]
    public virtual PurchaseOrder PurchaseOrder { get; set; }

    [InverseProperty("PurchaseOrderDetail")]
    public virtual ICollection<ReceiveOrderDetail> ReceiveOrderDetails { get; set; } = new List<ReceiveOrderDetail>();

    [InverseProperty("PurchaseOrderDetail")]
    public virtual ICollection<ReturnedOrderDetail> ReturnedOrderDetails { get; set; } = new List<ReturnedOrderDetail>();

    [ForeignKey("StockItemID")]
    [InverseProperty("PurchaseOrderDetails")]
    public virtual StockItem StockItem { get; set; }
}