// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ReceivingSystem.Entities;

public partial class UnOrderedItem
{
    [Key]
    public int UnOrderedItemID { get; set; }

    public int ReceiveOrderID { get; set; }

    public int ItemID { get; set; }

    [Required]
    [StringLength(50)]
    public string ItemName { get; set; }

    [Required]
    [StringLength(25)]
    public string VendorProductID { get; set; }

    public int Quantity { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("ReceiveOrderID")]
    [InverseProperty("UnOrderedItems")]
    public virtual ReceiveOrder ReceiveOrder { get; set; }

    [InverseProperty("UnOrderedItem")]
    public virtual ICollection<ReturnedOrderDetail> ReturnedOrderDetails { get; set; } = new List<ReturnedOrderDetail>();
}